Traceback (most recent call last):
  File "box_game_bk1.py", line 11, in <module>
pygame.error: Couldn't open C:\Users\wangkang\Desktop\box\image\help.png
